### ISSUE TITLE
transition to `cargo-make` when possible

### ISSUE THREAD

**Issue by Lokathor** [rust-console/gba#5]
Ketsuban suggested that we try out `cargo-make`

https://github.com/sagiegurari/cargo-make

It seems super cool, and if we can replace our `build.bat` file with something that'll work more properly on all platforms it'll be good.

**Comment by ketsuban** [comment]
This is the `Makefile.toml` I'm using right now.

```toml
[config]
skip_core_tasks = true

[env]
CARGO_MAKE_RUST_TARGET = "thumbv4-none-agb"

[tasks.default]
alias = "build"
workspace = false

[tasks.build]
command = "cargo"
args = ["xbuild", "--target", "${CARGO_MAKE_RUST_TARGET}.json"]
workspace = false

[tasks.release]
dependencies = ["release-step1", "release-step2", "release-step3"]
workspace = false

[tasks.release-step1]
command = "cargo"
args = ["xbuild", "--release", "--target", "${CARGO_MAKE_RUST_TARGET}.json"]

[tasks.release-step2]
command = "arm-none-eabi-objcopy"
args = ["-O", "binary", "target\\${CARGO_MAKE_RUST_TARGET}\\release\\finisterre", "target\\${CARGO_MAKE_RUST_TARGET}\\release\\finisterre.gba"]

[tasks.release-step3]
command = "gbafix"
args = ["target\\${CARGO_MAKE_RUST_TARGET}\\release\\finisterre.gba"]

[tasks.run]
dependencies = ["build"]
command = "C:\\mGBA\\mGBA.exe"
args = ["target\\${CARGO_MAKE_RUST_TARGET}\\debug\\finisterre"]
workspace = false
```

Caveats:

* I don't have a step for `crt0.s`, which I could probably stand to add.
* The `run` task is specific to my machine.
* Because I have a Cargo workspace rather than a single crate I can't use the `CARGO_MAKE_CRATE_FS_NAME` variable; feel free to replace the hardcoded `finisterre` in your own code.
